candidate_evaluation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', include('candidate.urls')),
	path('admin_home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    re_path(r'^captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    # print("url", settings.STATIC_ROOT, settings.STATIC_URL)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView
from . import views


app_name = 'users'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('allresults/', views.allresults, name='allresults'),
    path('topresults/', views.allfivestarresults, name='topresults'),
    path('<str:candidate_email>/', views.detail, name='detail'),
    path('<str:candidate_email>/results/', views.results, name='results'),
    path('<str:candidate_email>/evaluate/', views.evaluate, name='evaluate'),
]

templates/allresults.html
<!-- allresults.html -->
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="content">
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">All Candidates Results</h4>
                    </div>
                    <div class="card-body">

                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <table id="summary_table" class="table table-striped table-bordered display" style="width:100%">
                            <thead>
                            <tr >
                                <th>Name</th>
                                <th>Email</th>
                                <th>Verified By</th>
                                <th>Review Ratings</th>
                                <th>Detailed Result</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if data %}
                                {% for candidate in data %}
                                    <tr>
                                        <td><a href="{% url 'users:detail' candidate.contact_id.email %}">{{ candidate.contact_id.name }}</a></td>
                                        <td><a href="{% url 'users:detail' candidate.contact_id.email %}">{{ candidate.contact_id.email }}</a></td>
                                        <td>{{ candidate.verified_by }}</td>
                                        <td>{{ candidate.review_rating }}</td>
                                        <td class="text-center">  
                                            <a class="btn btn-round btn-info btn-icon btn-icon btn-sm download"
                                            href="{% url 'users:results' candidate.contact_id.email %}"
                                            style="align-content: center">
                                            <i class="material-icons">remove_red_eye</i></a> 
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %} 
                            </tbody>
                        </table>
                    </div><!-- end card body-->
                    <h4><li><a href="{% url 'logout' %}">Logout</a> | <a href="{% url 'users:allresults' %}">View All Results</a> | <a href="{% url 'users:topresults' %}">View Top Results</a></li></h4>
                </div><!--  end card  -->
            </div>
        </div>
      </div>
    </div>
  </div>



{% endblock %}

templates/base.html
<!-- templates/base.html -->

{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static '/assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static '/assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {% block title %}Candidate Evaluation{% endblock %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link rel="stylesheet" href="{% static '/assets/css/material-kit.css' %}">
</head>

<body class="profile-page sidebar-collapse">
  <nav class="navbar navbar-color-on-scroll navbar-transparent fixed-top navbar-expand-lg" color-on-scroll="100">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'users:dashboard' %}">
          <i class="material-icons">ac_unit</i>
          Candidate Evaluations Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="material-icons">account_circle</i> User
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="{% url 'login' %}" class="dropdown-item">
                <i class="material-icons">person</i> Login
              </a>
              <a href="{% url 'users:signup' %}" class="dropdown-item">
                <i class="material-icons">group_add</i> Siginup
              </a>
              <a href="{% url 'logout' %}" class="dropdown-item">
                <i class="material-icons">lock</i> Logout
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock %}
  <footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> for a better web.
      </div>
    </div>
  </footer>
	
    <!--   Core JS Files   -->
  <script src="{% static '/assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static '/assets/js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>

  <script src="{% static '/assets/js/plugins/moment.min.js' %}"></script>
  <script src="{% static '/assets/js/plugins/jquery.dataTables.min.js' %}"></script>
  <script src="{% static '/js/main.js' %}" type="text/javascript"></script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static '/assets/js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static '/assets/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!--  Plugin for Sharrre btn -->
  <script src="{% static '/assets/js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
  <!-- Control Center for Material Kit: parallax effects -->
  <script src="{% static '/assets/js/material-kit.min.js' %}" type="text/javascript"></script>

  <script>
    $(document).ready(function() {
      // //init DateTimePickers
      // materialKit.initFormExtendedDatetimepickers();

      // // Sliders Init
      // materialKit.initSliders();
    });


    $(document).ready(function() {

    $('#facebook').sharrre({
        share: {
          facebook: true
        },
        enableHover: false,
        enableTracking: false,
        enableCounter: false,
        click: function(api, options) {
          api.simulateClick();
          api.openPopup('facebook');
        },
        template: '<i class="fab fa-facebook-f"></i> Facebook',
        url: '#'
      });

      $('#googlePlus').sharrre({
        share: {
          googlePlus: true
        },
        enableCounter: false,
        enableHover: false,
        enableTracking: true,
        click: function(api, options) {
          api.simulateClick();
          api.openPopup('googlePlus');
        },
        template: '<i class="fab fa-google-plus"></i> Google',
        url: '#'
      });

      $('#twitter').sharrre({
        share: {
          twitter: true
        },
        enableHover: false,
        enableTracking: false,
        enableCounter: false,
        buttons: {
          twitter: {
            via: 'CreativeTim'
          }
        },
        click: function(api, options) {
          api.simulateClick();
          api.openPopup('twitter');
        },
        template: '<i class="fab fa-twitter"></i> Twitter',
        url: '#'
      });

      {% block javascript %}
      
      {% endblock javascript %}

    });
  </script>

</body>
</html>

templates/dashboard.html
<!-- dashboard.html -->
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
				<div class="card">
		            <div class="card-header">
		                <h4 class="card-title">All Candidates</h4>
		            </div>
		            <div class="card-body">

		                <div class="toolbar">
		                    <!--        Here you can write extra buttons/actions for the toolbar              -->
		                </div>
		                <table id="summary_table" class="table table-striped table-bordered display" style="width:100%">
			                <thead>
			                <tr >
			                    <th>Name</th>
			                    <th>Email</th>
			                    <th>Evaluate it</th>
			                </tr>
			                </thead>
			                <tbody>
			                {% if data %}
			                    {% for candidate in data %}
				                    <tr>
				                        <td><a href="{% url 'users:detail' candidate.email %}">{{ candidate.name }}</a></td>
				                        <td><a href="{% url 'users:detail' candidate.email %}">{{ candidate.email }}</a></td>
				                        <td class="text-center">  
				                            <a class="btn btn-round btn-info btn-icon btn-icon btn-sm download"
				                            href="{% url 'users:evaluate' candidate.email %}"
				                            style="align-content: center">
				                            <i class="material-icons">remove_red_eye</i></a>  
				                        </td>
				                    </tr>
				                {% endfor %}
				            {% endif %} 
			                </tbody>
		                </table>
		            </div><!-- end card body-->
		            <h4><ul><a href="{% url 'logout' %}">Logout</a> | <a href="{% url 'users:allresults' %}">View All Results</a> | <a href="{% url 'users:topresults' %}">View Top Results</a></ul></h4>
		        </div><!--  end card  -->
		    </div>
		</div>
      </div>
    </div>
  </div>



{% endblock %}

templates/detail.html
<!-- detail.html -->
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
				<div class="card">
		            <div class="card-header">
		                <h4 class="card-title">Details submitted by {{ candidate.name }} </h4>
		            </div>
		            <div class="row">
		            	<div class="col">
		            		<br />
		            		<br />
		            		<br />
		            		<div class="container">
		            			<h4>Name : {{ candidate.name }}</h4>
		            			<h4>Email Address : {{ candidate.email }}</h4>
		            			<h4>Web Address : {{ candidate.web_address }}</h4>
		            			<h4>Cover Letter : {{ candidate.cover_letter }}</h4>
		            			<h4>Like Working : 
		            				{% if candidate.like_working  == 1 %}
		            					Yes
		            				{% else %}
		            					No
		            				{% endif %}
		            			</h4>
		            		</div>
		            	</div>
		            	<div class="col">
		            		<embed src="{{ candidate.file_path }}" content_type="application/pdf" height="700px" width="500">
		            	</div>
		            </div>
		            <h4><ul>
		            	<a href="{% url 'users:evaluate' candidate.email %}"> Evaluate {{ candidate.email }}</a> |
						<a href="{% url 'users:results' candidate.email %}"> See Results {{ candidate.email }}</a> |
						<a href="{% url 'users:dashboard' %}"> GoTo Dashboard</a>
					</ul></h4>
		        </div>
		    </div>
		</div>
      </div>
    </div>
  </div>

{% endblock %}

templates/evaluate.html
<!-- templates/register.html -->
{% extends 'base.html' %}

{% block title %}Evaluate{% endblock %}

{% block content %}

{% load widget_tweaks %}
  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="content">
            <div class="row">
            <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Evaluation form</h4>
                    </div>
                    <div class="card-body">
                      <div class="container" id="{{ data }}">
                        <br />
                        <br />
                        <br />
                        <form method="post" enctype="multipart/form-data" novalidate>
                          {% csrf_token %}

                          {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                          {% endfor %}

                          <div class="container">
                            {% if form.non_field_errors %}
                              <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                  {{ error }}
                                {% endfor %}
                              </div>
                            {% endif %}

                            {% if data == "fail" %}
                              <div class="alert alert-danger" role="alert">
                                {% for error in form.non_field_errors %}
                                  {{ error }}
                                {% endfor %}
                              </div>
                            {% endif %}

                          </div>

                          {% for field in form.visible_fields %}
                            <div class="form-group">
                              {{ field.label_tag }}

                              {% if form.is_bound %}
                                {% if field.errors %}
                                  {% render_field field class="form-control is-invalid" %}
                                  {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                      {{ error }}
                                    </div>
                                  {% endfor %}
                                {% else %}
                                  {% render_field field class="form-control is-valid" %}
                                {% endif %}
                              {% else %}
                                {% render_field field class="form-control" %}
                              {% endif %}

                              {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                              {% endif %}
                            </div>
                          {% endfor %}

                          <br />
                          <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                        </form>
                      </div>
                    </div><!-- end card body-->
                    <h4><ul><a href="{% url 'users:dashboard' %}">Dashboard</a> | <a href="{% url 'users:allresults' %}">View All Results</a> | <a href="{% url 'users:topresults' %}">View Top Results</a></ul></h4>
                </div><!--  end card  -->
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
				<div class="card">
		            <div class="card-body">
		            	{% if user.is_authenticated %}
						  Hi {{ user.username }}!
						  <ul><h3><a href="{% url 'users:dashboard' %}">Evaluate Candidate</a> | <a href="{% url 'logout' %}">logout</a></h3></ul>
						{% else %}
						  <p>You are not logged in</p>
						  <ul><h3><a href="{% url 'login' %}">login</a> | <a href="{% url 'users:signup' %}">signup</a></h3></ul>
						{% endif %}
		            </div><!-- end card body-->
		        </div><!--  end card  -->
		    </div>
		</div>
      </div>
    </div>
  </div>

{% endblock %}

templates/result.html
<!-- result.html -->
{% extends 'base.html' %}

{% block title %}Result{% endblock %}

{% block content %}

  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
		    {% if data %}
				{% for candidate in data %}
				<div class="card">
		            <div class="card-header">
		                <h4 class="card-title">Result of {{ candidate.contact_id.email }}</h4>
		            </div>
		            <div class="card-body">
						<p>Name of Candidate: {{ candidate.contact_id.name }}</p>
						<p>Web address: {{ candidate.contact_id.web_address }}</p>
						<p>Reviewed By: {{ candidate.verified_by }}</p>
						<p>Reviewers Comment: {{ candidate.comment }}</p>
						<p>Reviewers Rating: {{ candidate.review_rating }}</p>
						<p>Reviewed On: {{ candidate.verified_on }}</p>
					</div><!-- end card body-->
		        </div><!--  end card  -->
				{% endfor %}
			{% else %}
			    <p>No candidates are available.</p>
			{%endif%}
			<h4><ul><a href="{% url 'logout' %}">Logout</a> | <a href="{% url 'users:allresults' %}">View All Results</a> | <a href="{% url 'users:topresults' %}">View Top Results</a></ul></h4>
		    </div>
		</div>
      </div>
    </div>
  </div>


{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}


  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
				<div class="card">
		            <div class="card-body">
		            	<h2>Sign up</h2>
						<form method="post">
						  {% csrf_token %}
						  {{ form.as_p }}
						  <button type="submit">Sign up</button>
						</form>
		            </div><!-- end card body-->
		        </div><!--  end card  -->
		    </div>
		</div>
      </div>
    </div>
  </div>


{% endblock %}

templates/topresults.html
<!-- topresults.html -->
{% extends 'base.html' %}

{% block title %}Top Results{% endblock %}

{% block content %}

  <div class="page-header header-filter clear-filter purple-filter" data-parallax="true">
  	<div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand text-center">
            <h1>Candidate Evaluation</h1>
            <h3 class="title text-center">Evaluate Candidate at ease</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
		<div class="content">
		    <div class="row">
				<div class="card">
		            <div class="card-header">
		                <h4 class="card-title">All Top Results</h4>
		            </div>
		            <div class="card-body">

		                <div class="toolbar">
		                    <!--        Here you can write extra buttons/actions for the toolbar              -->
		                </div>
		                <table id="summary_table" class="table table-striped table-bordered display" style="width:100%">
			                <thead>
			                <tr >
			                    <th>Name</th>
			                    <th>Email</th>
			                    <th>Review Ratings</th>
			                    <th>Reviewed By</th>
			                </tr>
			                </thead>
			                <tbody>
			                {% if data %}
			                    {% for candidate in data %}
				                    <tr>
				                        <td><a href="{% url 'users:detail' candidate.contact_id.email %}">{{ candidate.contact_id.name }}</a></td>
				                        <td><a href="{% url 'users:detail' candidate.contact_id.email %}">{{ candidate.contact_id.email }}</a></td>
				                        <td><a href="{% url 'users:results' candidate.contact_id.email %}">{{ candidate.review_rating }}</a></td>
				                        <td><a href="{% url 'users:results' candidate.contact_id.email %}">{{ candidate.verified_by }}</a></td>
				                    </tr>
				                {% endfor %}
				            {% endif %} 
			                </tbody>
		                </table>
		            </div><!-- end card body-->
		            <h4><ul><a href="{% url 'logout' %}">Logout</a> | <a href="{% url 'users:allresults' %}">View All Results</a> | <a href="{% url 'users:topresults' %}">View Top Results</a></ul></h4>
		        </div><!--  end card  -->
		    </div>
		</div>
      </div>
    </div>
  </div>


{% endblock %}